### PR TITLE
[BUGFIX] Fix undefined variables access (PHP 8+ compatibility)

### LINKED ISSUE #1217: Undefined variables access with PHP 8+
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.3
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

In class `\BK2K\BootstrapPackage\ViewHelpers\Data\ImageVariantsViewHelper`, method `ImageVariantsUtility::getImageVariants` is called without checking if any of the arguments are actually defined.

In class `\BK2K\BootstrapPackage\ViewHelpers\Format\TrimViewHelper` the result to be trimmed may actually be null.

## Steps to Reproduce

1. Have some Fluid calling the `\BK2K\BootstrapPackage\ViewHelpers\Data\ImageVariantsViewHelper` without all arguments
2. Have some Fluid calling the `\BK2K\BootstrapPackage\ViewHelpers\Format\TrimViewHelper` without content

### Expected behavior

No PHP error, nothing should actually happen. The `\BK2K\BootstrapPackage\ViewHelpers\Format\TrimViewHelper` should return an empty string.

### Actual behavior

A PHP error

## Versions

12.0.5

### PR DESCRIPTION
**Pull request by fsuter**
# Pull Request

## Related Issues

* Fixes #1217

## Prerequisites

* [ ] Changes have been tested on TYPO3 v10.4 LTS
* [x ] Changes have been tested on TYPO3 v11.5 LTS
* [ ] Changes have been tested on PHP 7.2
* [ ] Changes have been tested on PHP 7.3
* [ ] Changes have been tested on PHP 7.4
* [x ] Changes have been tested on PHP 8.0
* [ ] Changes have been checked for CGL compliance `php-cs-fixer fix`

## Description

Assign sane fallback values using the coalesce operator.

## Steps to Validate

1. See related issue

### CODE REVIEW

File: Classes/ViewHelpers/Format/TrimViewHelper.php [hunk 1]
```diff
@@ -29,6 +29,6 @@ class TrimViewHelper extends AbstractViewHelper
      */
     public static function renderStatic(array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext)
     {
-        return trim($renderChildrenClosure());
+        return trim($renderChildrenClosure()) ?? '';
```
Comment (fsuter) [inline Classes/ViewHelpers/Format/TrimViewHelper.php:32]: Sorry, I made an error when copy-pasting my patch around. It should be:
`return trim($renderChildrenClosure() ?? '');`
I don't know how to update a pull request.

Comment (SvenJuergens) [reply Classes/ViewHelpers/Format/TrimViewHelper.php:32]: @fsuter 
Push to the branch you created the pull request from and it should be automatic updated.

**Review by oliverklee — APPROVED** [review]
