### PR TITLE
[BUGFIX] Google font caching

### LINKED ISSUE #1604: Google Fonts not cached
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v13.4 LTS
* [x] Can you reproduce the problem on TYPO3 v14.0 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description
In Version 16.0 no Google Fonts Cache generated.
https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/Service/GoogleFontService.php
1. if Font name in $url is a Single Word (Lato) the $content Variable in L73 will become empty in L75.
2. If Font Name in $url has Spaces (Source Sans Pro" the isValidHttpsUrl() Function will fail.

## Steps to Reproduce

1. change Fontname in Settings
2. reload Page
3. public/typo3temp/assets/bootstrappackage/fonts/*/ has only a empty webfont.css

### Expected behavior
Fonts and webfont.css will be created 

## Versions
"bk2k/bootstrap-package": "^16.0.0",

### PR DESCRIPTION
**Pull request by buchmarv**
# Pull Request

## Related Issues

* Fixes #1604

## Prerequisites

* [x] Changes have been tested on TYPO3 v13.4 LTS
* [x] Changes have been tested on TYPO3 v14.1
* [x] Changes have been tested on PHP 8.2
* [ ] Changes have been tested on PHP 8.3
* [x] Changes have been tested on PHP 8.4
* [x] Changes have been checked for CGL compliance `php-cs-fixer fix`
* [ ] CSS has been rebuilt (only if there are SCSS changes `cd Build; npm ci; npm run build`)

## Description

Currently, there are two issues with Google fonts caching:
1. Response stream is fetched twice, resulting in empty cache files.
2. In v13 validation of URLs fails with font family names containing white spaces as they were not properly encoded. Since white spaces are commonly used in Google fonts URLs, they are simply replaced.

### Empty cache files

1. Install extension from master branch, keep default settings.
2. Check the generated cache file being empty.
3. Install extension from this branch, keep default settings.
4. Check the generated cache file containing desired content.

### No caching in v13 with white spaces in font family names

1. Install extension from master branch in v13, keep default settings.
2. Check the frontend loading fonts from fonts.googleapis.com.
3. Install extension from this branch in v13, keep default settings.
4. Check the frontend loading fonts from the cache file.

### CODE REVIEW

File: Classes/Service/GoogleFontService.php [hunk 1]
```diff
@@ -117,7 +115,9 @@ protected function cacheUrl(string $url): bool
 
     protected function isValidHttpsUrl(string $url): bool
     {
-        return filter_var($url, FILTER_VALIDATE_URL) !== false
+        // as prior to TYPO3 v14 arguments were not encoded, and it's common to use whitespaces in Google font URLs,
```
Comment (andreaskienast) [inline Classes/Service/GoogleFontService.php:118]: Apparently this isn't covered by tests (at least I didn't find any). Can we add a new test case to [Tests/Unit/Service/GoogleFontServiceTest.php](https://github.com/benjaminkott/bootstrap_package/blob/master/Tests/Unit/Service/GoogleFontServiceTest.php)?

**Review by andreaskienast — APPROVED** [review]
lgtm

**Comment by tkieslich** [comment]
Thanks

**Comment by simonschaufi** [comment]
@benjaminkott would it be possible to create a new release soon with this patch? This bug currently breaks loading of google fonts as the css file will be empty
